// Code generated by "Myself"; PLEASE EDIT.

package views

import (
	"instafix/views/model"
	"io"
)

const (
	oembed__0 = `{"author_name": `
	oembed__1 = `,"author_url": "`
	oembed__2 = `","provider_name": "InstaFix","provider_url": "https://github.com/Wikidepia/InstaFix","title": "Instagram","type": "link","version": "1.0"}`
)

func OEmbed(o *model.OEmbedData, wr io.Writer) {
	buffer := &WriterAsBuffer{wr}

	buffer.WriteString(oembed__0)
	WriteAll(o.Text, false, buffer) // Escape in handlers
	buffer.WriteString(oembed__1)
	WriteAll(o.URL, false, buffer) // Escape in handlers
	buffer.WriteString(oembed__2)

}
